### ISSUE TITLE
 Prepare for v0.1.0

### ISSUE THREAD

**Issue by sdpkjc** [sdpkjc/abcdrl#8]
- [x] Support wandb tag in script #10 
- [x] Issues & Pull requests Template #13 
- [x] Licence Ref #15 
- [x] Wrapper overhaul #16
- [x] Add mypy type-hint check in pre-commit #17 
- [x] Scripts and examples overhaul #20 
- [x] DQN in Atari env #25 
- [x] Benchmark #33 
- [x] tutorial of run and modify alg #52

**Comment by sdpkjc** [comment]
Close #8

**Comment by sdpkjc** [comment]
Close #8
